FROM php:8.1-alpine

RUN apk --no-cache add \
        zip \
        unzip \
        git \
        libzip-dev \
        autoconf \
        g++ \
        make \
        linux-headers

RUN pecl install xdebug  \
       && docker-php-ext-enable  xdebug

RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

WORKDIR /app/boilerplate-laravel-10

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer
RUN COMPOSER_ALLOW_SUPERUSER=1

COPY . .

RUN COMPOSER_VENDOR_DIR="/app/boilerplate-laravel-10/vendor"
RUN composer install --ignore-platform-req=ext-sockets


CMD ["sh"]

