version: '3.5'
services:
  boilerplate-laravel-10-serverless:
    container_name: boilerplate-laravel-10-serverless
    build: .
    volumes:
      - .:/app/boilerplate-laravel-10-serverless
      - volume-boilerplate-laravel-10-serverless-vendor:/app/boilerplate-laravel-10-serverless/vendor
      - volume-boilerplate-laravel-10-serverless-node_modules:/app/boilerplate-laravel-10-serverless/node_modules
    networks:
      - boilerplate-laravel-10-serverless-network
      - mysql-network
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
 volume-boilerplate-laravel-10-serverless-vendor:
  name: volume-boilerplate-laravel-10-serverless-vendor
 volume-boilerplate-laravel-10-serverless-node_modules:
  name: volume-boilerplate-laravel-10-serverless-node_modules

networks:
   boilerplate-laravel-10-serverless-network:
    name: boilerplate-laravel-10-serverless-network
    driver: bridge
   mysql-network:
    name: mysql-network
    external: true

