service: boilerplate-laravel-10-serverless

provider:
    name: aws
    region: us-east-2
    environment:
        APP_ENV: ${sls:stage}
        APP_NAME: TEST
custom:
  functionsDir: Src/Infra/Functions
  stage: ${sls:stage}
package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
resources:
   - "${file(devops/sns.yml)}"
functions:
   - ${file(${self:custom.functionsDir}/Web/handler.yml)}
   - ${file(${self:custom.functionsDir}/Console/handler.yml)}
   - ${file(${self:custom.functionsDir}/SNS/Example/_handlers.yml)}
plugins:
    - ./vendor/bref/bref
