service: boilerplate-laravel-10-serverless

provider:
    name: aws
    region: us-east-2
    environment:
        APP_ENV: ${sls:stage}
        APP_NAME: TEST
custom:
  functionsDir: ./src/Infra/Functions
package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
functions:
    ${file(${self:custom.functionsDir}/Web/handler.yml)}
plugins:
    - ./vendor/bref/bref



