name: DEPLOY - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install Node Dependencies
        run: npm ci
    # - name: Configure aws credentials
      # run: npx serverless config credentials --provider aws --key "key" --secret "secret"
      - name: npx serverless deploy
        run: npm ci
