name: DEPLOY - STG
on:
   workflow_dispatch:
    inputs:
      run_migration:
        type: boolean
        default: false
        description: Run migration into database
jobs:
  serverless:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/laravel-serverless-deploy.yml@master
    with:
      php_version: '8.1'
      run_migration: ${{github.event.inputs.run_migration}}
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_STG}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_STG}}