name: DESTROY - DEV
on:
   workflow_dispatch:
jobs:
  serverless:
    name: destroy
    uses: GabrielSoares-Dev/workflows/.github/workflows/laravel-serverless-destroy.yml@master
    with:
      php_version: '8.1'
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_DEV}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_DEV}}